title: Sonali Bokikere Sreedhar # your name (or website title) here
logo: "/images/IMG_4658 2 (1).jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 USC-2020|Data Science|Computer Vision|DSP 
  <br><br>
  Looking for Co-ops-2020| Full Time Opportunities starting from Jan 2021.
 I hope to combine my  experience working as an Applications Engineer at Analog Devices added  with the skills and concepts learned in this program will help me advance in the upcoming exciting field . I believe my creativity, enthusiasm for the field, and maker mentality will be assets to any team I join in the future.
  
  <a href="https://www.linkedin.com/in/sonali-b-s">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
