title: Sonali Bokikere Sreedhar # your name (or website title) here
logo: "/images/IMG_4658 2 (1).jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 USC-2020|Data Science|Computer Vision|DSP 
  <br><br>
  Looking for Co-ops-2020| Full Time Opportunities starting from Jan 2021.
  <br><br>
 
  
  <a href="https://www.linkedin.com/in/sonali-b-s">View My LinkedIn Profile</a> 
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en" style="width:100%; height:100%;">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>kekayan's Resume</title>
</head>
  <body style="width:100%; height:100%; margin:0;">
    <iframe src="https://docs.google.com/gview?url= https://github.com/sbsreedh/Resume/blob/master/SONALI_SREEDHAR_v_29.pdf &embedded=true" style="width:100%; height:100%;" frameborder="0"></iframe>
  </body>
</html>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
