title: Sonali Bokikere Sreedhar # your name (or website title) here
logo: "/images/IMG_4658 2 (1).jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Currently pursuing my MS in Electrical Engineering at  University Of Southern California , I intend to focus on areas such as  machine learning, AI, computer vision, embedded systems, and algorithm development . I hope to combine my  experience working as an Applications Engineer at Analog Devices added  with the skills and concepts learned in this program will help me advance in the upcoming exciting field . I believe my creativity, enthusiasm for the field, and maker mentality will be assets to any team I join in the future.
  
  <a href="https://www.linkedin.com/in/sonali-b-s">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
