title: Sonali Bokikere Sreedhar # your name (or website title) here
logo: "/images/IMG_4658 2 (1).jpg?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 USC-2020|Data Science|Computer Vision|DSP 
  <br><br>
  Looking for Co-ops-2020| Full Time Opportunities starting from Jan 2021.
  <br><br>
 
  
  <a href="https://www.linkedin.com/in/sonali-b-s">View My LinkedIn Profile</a> 
   <br><br>
  <a href="https://https://github.com/sbsreedh/Resume/blob/master/SONALI_SREEDHAR_v_29.pdf">View My Resume</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
